# Generated by Django 2.2.28 on 2023-11-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('quantite_disponible', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('Achat', 'Achat'), ('Vente', 'Vente')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Actif')),
            ],
        ),
    ]
