# Generated by Django 2.2.28 on 2023-11-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actif',
            name='etat',
            field=models.CharField(choices=[('Non détenu', 'Non détenu'), ('Acheté', 'Acheté')], default='Non détenu', max_length=20),
        ),
    ]
