# Generated by Django 2.2.28 on 2023-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portefeuille'),
    ]

    operations = [
        migrations.AddField(
            model_name='actif',
            name='lien_web',
            field=models.URLField(default='https://fr.finance.yahoo.com/quote/AAPL'),
            preserve_default=False,
        ),
    ]
